// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybdaeonctdbgmspabkab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZGFlb25jdGRiZ21zcGFia2FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTI5MjMsImV4cCI6MjA2MzkyODkyM30.oZp5zvFFMGA8_h7F3J4P2mDA_7ovRlxgcKPTXkArZLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);